#interface control ---
interface=eth0
bind-interfaces
except-interface=lo

# --- DNS ---
no-resolv
server=1.1.1.1
server=8.8.8.8
cache-size=1000
domain-needed
bogus-priv

# --- Local hostnames ---
#domain=lab.local
#address=/router.lab.local/192.168.1.1
#expand-hosts

# --- DHCP ---
#dhcp-range=192.168.1.50,192.168.1.150,255.255.255.0,12h
#dhcp-option=option:router,192.168.1.1
#dhcp-option=option:dns-server,192.168.1.1
#dhcp-host=aa:bb:cc:dd:ee:ff,192.168.1.20,my-server

# --- Logging ---
#log-queries
#log-dhcp
#log-facility=/var/log/dnsmasq.log
