frr version 10.3
frr defaults traditional
hostname iBGP1
log syslog informational
service integrated-vtysh-config
!
interface eth1
 ip address 172.16.0.3/24
exit
!
interface l0
 ip address 1.1.1.1/32
exit
!
router ospf
 network 1.1.1.1/32 area 0
 network 172.16.0.0/24 area 0
exit
!
segment-routing
 traffic-eng
 exit
exit
!
