frr version 10.3
frr defaults traditional
hostname iBGP2
log syslog informational
service integrated-vtysh-config
!
interface eth0
 ip address 192.168.1.1/30
exit
!
interface eth1
 ip address 172.16.0.4/24
exit
!
interface eth4
 ip address 192.168.2.2/30
exit
!
interface l
 ip address 10.10.10.3/32
exit
!
interface l0
 ip address 2.2.2.2/32
exit
!
interface lo
 ip address 10.10.10.3/32
exit
!
router bgp 65001
 neighbor 10.10.10.1 remote-as 65001
 neighbor 10.10.10.1 update-source lo
 neighbor 10.10.10.2 remote-as 65001
 neighbor 10.10.10.2 update-source lo
exit
!
router ospf
 network 2.2.2.2/32 area 0
 network 10.10.10.3/32 area 0
 network 172.16.0.0/24 area 0
 network 192.168.0.0/16 area 0
 default-information originate
exit
!
segment-routing
 traffic-eng
 exit
exit
!
