frr version 10.3
frr defaults traditional
hostname FRRDocker-5
log syslog informational
service integrated-vtysh-config
!
interface eth0
 ip address 192.168.5.10/24
exit
!
segment-routing
 traffic-eng
 exit
exit
!
